# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "cent"
  config.vm.box = "centos/8"
  config.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1"
  config.vm.synced_folder ".", "/home/vagrant/app"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
end
